line-length = 120

[lint]
select = ["E", "F", "I", "RUF022"]
ignore = ["E501", "E402"]

[lint.per-file-ignores]
"scripts/*" = ["E402"]
"database/models.py" = ["E402"]
"tests/*" = ["E402"]
"bot/registration_parts/*" = ["E402"]
